services:
  rabbit-mq:
    image: rabbitmq:management
    container_name: rabbit-mq-container
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 3s
      timeout: 3s
      retries: 30
